spring:
  datasource:
    url: jdbc:h2:tcp://localhost/E:/h2/shop;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        storage_engine: innodb
        use_sql_comments: true

logging:
  level:
    org.hibernate.SQL: debug
